### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Bump version for #7

### CODE REVIEW

**Comment by jkarsrud** [comment]
@sivakumar-kailasam I'm looking into what seems to be a bug with setting the namespace properly from the options, which also makes me wonder if #7 will break the actual defeatureifying of the app. I'm not willing to bump this just yet. Before I do so, you can specify your fork in your project?

**Comment by sivakumar-kailasam** [comment]
> Before I do so, you can specify your fork in your project?

Sorry didn't get this part

**Comment by jkarsrud** [comment]
I mean, before this project is bumped to 1.0.2, you can specify you own fork of this project (https://github.com/sivakumar-kailasam/ember-cli-defeatureify) with the fixes in your package.json (https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by sivakumar-kailasam** [comment]
already using that :smiley:

**Pull request closed without merging**
