### PR TITLE
Move to modules.

### LINKED ISSUE #15: Generate a module instead of using globals.
I'd like to move away from inserting feature state as a global inside of `app-prefix` to make it easier to move to a modules-only world. See: https://github.com/ember-cli/ember-cli/issues/5240

As a result I would want to modify ember-cli-defeatureify to generate a module which could be included into any ember app's module that needs defeatureifying:

``` javascript
import myNamespace from 'ember-cli-defeatureify/config';
```

The change for any existing users of this addon would be the above mechanical change. Would you accept a PR for this functionality?

### PR DESCRIPTION
**Pull request by nathanhammond**
`ember-cli-defeatureify` presently requires globals since the processing for feature stripping does a string comparison on the variable path. This PR implements a solution that allows for importing of the feature configuration as a module and removes globals. As a consequence there is no longer any need to specify `namespace` as that will consistently be the module name.

This also dramatically reduces the complexity of the addon. I've also ported it to an up-to-date blueprint.

Depends on https://github.com/ember-cli/ember-cli/pull/5233/ landing in order to support configuration in a meta tag.

Closes #15.

### CODE REVIEW

**Comment by nathanhammond** [comment]
Also, @jkarsrud, I've added you as a collaborator to my fork in case you want to modify this PR so you can do so directly in my fork.

**Comment by jkarsrud** [comment]
@nathanhammond I've given you commit access to this repo now, so feel free to do changes as you wish. I don't really use this addon anymore, so it's better if someone who actually does maintains it :)

**Comment by nathanhammond** [comment]
@jkarsrud Awesome, thanks! We're still looking for the world's most ridiculous bug which is preventing https://github.com/ember-cli/ember-cli/pull/5233 from landing, but that's really the only thing left.

**Comment by erkie** [comment]
Any chance of getting this merged? Looking forward to getting rid of the deprecation:

```
DEPRECATION: The `app-prefix` hook used in ember-cli-defeatureify is deprecated. The addon should generate a module and have consumers `require` it.
```

:D

**Pull request closed without merging**
